apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: allow-grafana-userid-472
# allowPrivilegedContainer: true
fsGroup:
  type: MustRunAs
  ranges:
    - max: 472
      min: 472
runAsUser:
  type: RunAsAny
  # ranges:
  #   - max: 0
  #     min: 472
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: MustRunAs
  ranges:
    - max: 472
      min: 472
volumes:
  - configMap
  - emptyDir
  - persistentVolumeClaim
  - secret
