apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhdg8-cluster
  annotations:
    description: Template to deploy a RHDG cluster on OCP.
    tags: infinispan,datagrid,operator
    iconClass: icon-datagrid
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${CLUSTER_NAME}
    namespace: ${CLUSTER_NAMESPACE}
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${CLUSTER_NAME}-credentials
    namespace: ${CLUSTER_NAMESPACE}
  labels:
    type: middleware
  type: Opaque 
  stringData: 
    identities.yaml: |-     
      credentials:
      - username: developer
        password: developer
      - username: operator
        password: ${OPERATOR_PASSWORD}
      - username: prometheus
        password: ${PROMETHEUS_PASSWORD}
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${CLUSTER_NAME}-caches-credentials
    namespace: ${CLUSTER_NAMESPACE}
  labels:
    type: middleware
  type: Opaque 
  stringData:
    username: operator
    password: ${OPERATOR_PASSWORD}
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${CLUSTER_NAME}-monitoring-credentials
    namespace: ${CLUSTER_NAMESPACE}
  labels:
    type: middleware
  type: Opaque 
  stringData:
    username: prometheus
    password: ${PROMETHEUS_PASSWORD}
- apiVersion: infinispan.org/v1
  kind: Infinispan
  metadata:
    name: ${CLUSTER_NAME}
    namespace: ${CLUSTER_NAMESPACE}
    labels:
      type: middleware
  spec:
    # affinity:
    #   nodeAffinity:
    #     preferredDuringSchedulingIgnoredDuringExecution:
    #       - preference:
    #         weight:
    #     requiredDuringSchedulingIgnoredDuringExecution: 
    #       nodeSelectorTerms:
    #         - matchExpressions:
    #           matchFields:
    #   podAffinity:
    #     preferredDuringSchedulingIgnoredDuringExecution:
    #       - podAffinityTerm:
    #         weight:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       - labelSelector:
    #         namespaces:
    #         topologyKey:
    #   podAntiAffinity:
    #     preferredDuringSchedulingIgnoredDuringExecution:
    #       - podAffinityTerm:
    #         weight:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       - labelSelector:
    #         namespaces:
    #         topologyKey:
    # autoscale:
    #   disabled:
    #   maxMemUsagePercent:
    #   maxReplicas:
    #   minMemUsagePercent:
    #   minReplicas:
    container:
      cpu: '2'
      extraJvmOpts: '-Xlog:gc*=info:file=/tmp/gc.log:time,level,tags,uptimemillis:filecount=10,filesize=1m
              -XX:-UseParallelOldGC -XX:+UseG1GC -XX:MaxGCPauseMillis=400'
      memory: 3Gi
    expose: 
      annotations: {}
      # host:
      # nodePort:
      type: Route
    # image: "infinispan/server:12.0"
    logging:
      categories:
        org.jgroups.protocols.TCP: error
        org.jgroups.protocols.relay.RELAY2: error
    replicas: 3
    security:
      endpointEncryption:
        # certSecretName: ${CLUSTER_NAME}-cert-secret
        # certServiceName: ${CLUSTER_NAME}.${CLUSTER_NAMESPACE}.svc
        type: None 
      endpointSecretName: ${CLUSTER_NAME}-credentials
    service:
      # container:
      #   ephemeralStorage:
      #   storage: ''
      #   storageClassName:
      # replicationFactor: 2
      sites:
        local:
          expose:
            # annotations: {}
            # nodePort:
            type: LoadBalancer
          name: ${CLUSTER_NAME}
        locations:
          - #clusterName: ${CLUSTER_NAME}
            name: ${CLUSTER_NAME}
            namespace: ${CLUSTER_NAMESPACE}
            secretName: ${CLUSTER_NAME}-xsite-secret
            url: openshift://api.apps.cluster-2688q.2688q.sandbox40.opentlc.com:6443
          - #clusterName: ${CLUSTER_NAME_XSITE_REMOTE}
            name: ${CLUSTER_NAME_XSITE_REMOTE}
            namespace: ${CLUSTER_NAMESPACE_XSITE_REMOTE}
            secretName: ${CLUSTER_NAME_XSITE_REMOTE}-xsite-secret
            url: openshift://api.apps.cluster-2688q.2688q.sandbox40.opentlc.com:6443
      type: DataGrid
parameters:
# Local cluster data
- name: CLUSTER_NAMESPACE
  description: "The project of the local RHDG cluster."
  required: false
  value: "rhdg8-xsite-01"
- name: CLUSTER_NAME
  description: "The name of the local xsite RHDG cluster."
  required: false
  value: "rhdg-xsite-01"
# Remote cluster data
- name: CLUSTER_NAMESPACE_XSITE_REMOTE
  description: "The project of the remote RHDG cluster."
  required: false
  value: "rhdg8-xsite-02"
- name: CLUSTER_NAME_XSITE_REMOTE
  description: "The name of the remote xsite RHDG cluster."
  required: false
  value: "rhdg-xsite-02"
# Passwords
- name: PROMETHEUS_PASSWORD
  description: "Password used by Prometheus to obtain metrics from /metrics."
  required: true
  from: '[a-zA-Z0-9]{20}'
  generate: expression
- name: OPERATOR_PASSWORD
  description: "Password used by the Operator to create caches."
  required: true
  from: '[a-zA-Z0-9]{20}'
  generate: expression