apiVersion: v1
kind: Template
metadata:
  name: grafana-datasource
  annotations:
    description: Template to create a Grafana data source on OCP.
    tags: grafana,community,operator
    iconClass: icon-cassandra
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: integreatly.org/v1alpha1
  kind: GrafanaDataSource
  metadata:
    name: prometheus-grafana-datasource
    namespace: ${OPERATOR_NAMESPACE}
  spec:
    datasources:
      - access: proxy
        editable: true
        isDefault: true
        jsonData:
          httpHeaderName1: 'Authorization'
          timeInterval: 5s
          tlsSkipVerify: true
        name: OCPPrometheus
        secureJsonData:
          httpHeaderValue1: 'Bearer ${BEARER_TOKEN}'
        type: prometheus
        url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
    name: prometheus-grafana-datasource.yaml
parameters:
- name: OPERATOR_NAMESPACE
  description: "The project where the operator will be installed."
  required: false
  value: "grafana-operator"
- name: BEARER_TOKEN
  description: "Bearer token of the SA."
  required: true
  value: ""