apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: infinispan-operator
  annotations:
    description: Template to deploy a Infinispan operator on OCP.
    tags: infinispan,datagrid,operator
    iconClass: icon-infinispan
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${OPERATOR_NAMESPACE}
    annotations:
      openshift.io/description: "This project contains all the resources related to the operator of Infinispan"
      openshift.io/display-name: "Infinispan - Operator"
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${CLUSTER_NAMESPACE}
    annotations:
      openshift.io/description: "This project contains all the clusters deployed of Infinispan"
      openshift.io/display-name: "Infinispan"
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: infinispan
    namespace: ${OPERATOR_NAMESPACE}
  spec:
    targetNamespaces:
      - ${CLUSTER_NAMESPACE}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: datagrid-operator
    namespace: ${OPERATOR_NAMESPACE}
  spec:
    channel: 2.1.x
    installPlanApproval: Automatic
    name: infinispan
    source: community-operators
    sourceNamespace: openshift-marketplace
parameters:
- name: OPERATOR_NAMESPACE
  description: "The project where the operator will be installed."
  required: false
  value: "infinispan-operator"
- name: CLUSTER_NAMESPACE
  description: "The project where the Infinispan cluster will be installed."
  required: false
  value: "infinispan"