apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhdg8-cluster
  annotations:
    description: Template to deploy a RHDG cluster on OCP.
    tags: infinispan,datagrid,operator
    iconClass: icon-datagrid
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: infinispan.org/v1
  kind: Infinispan
  metadata:
    name: ${CLUSTER_NAME}
    namespace: ${CLUSTER_NAMESPACE}
    annotations:
      infinispan.org/monitoring: 'false'
      # infinispan.org/podTargetLabels: prometheus_domain
      infinispan.org/targetLabels: prometheus_domain
    labels:
      type: middleware
      prometheus_domain: ${CLUSTER_NAME}
  spec:
    # affinity:
    #   nodeAffinity:
    #     preferredDuringSchedulingIgnoredDuringExecution:
    #       - preference:
    #         weight:
    #     requiredDuringSchedulingIgnoredDuringExecution: 
    #       nodeSelectorTerms:
    #         - matchExpressions:
    #           matchFields:
    #   podAffinity:
    #     preferredDuringSchedulingIgnoredDuringExecution:
    #       - podAffinityTerm:
    #         weight:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       - labelSelector:
    #         namespaces:
    #         topologyKey:
    #   podAntiAffinity:
    #     preferredDuringSchedulingIgnoredDuringExecution:
    #       - podAffinityTerm:
    #         weight:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       - labelSelector:
    #         namespaces:
    #         topologyKey:
    # autoscale:
    #   disabled:
    #   maxMemUsagePercent:
    #   maxReplicas:
    #   minMemUsagePercent:
    #   minReplicas:
    container:
      cpu: '2'
      extraJvmOpts: '-Xlog:gc*=info:file=/tmp/gc.log:time,level,tags,uptimemillis:filecount=10,filesize=1m
              -XX:-UseParallelOldGC -XX:+UseG1GC -XX:MaxGCPauseMillis=400'
      memory: 3Gi
    expose: 
      annotations: {}
      # host:
      # nodePort:
      type: Route
    # image: "infinispan/server:12.0"
    logging:
      categories: {}
      # categories:
      #   org.infinispan: debug
      #   org.jgroups: debug
    replicas: 3
    security:
      endpointEncryption:
        # certSecretName:
        # certServiceName:
        type: None
      endpointAuthentication: false
      # endpointSecretName: ${CLUSTER_NAME}-credentials
    service:
      container:
        ephemeralStorage: true
      #   storage: ''
      #   storageClassName:
      # replicationFactor: 2
      # sites:
      #   local:
      #     expose:
      #       annotations: {}
      #       host:
      #       nodePort:
      #       type:
      #     name:
      #   locations:
      #     - host:
      #       name:
      #       port:
      #       secretName:
      #       url:
      type: DataGrid
parameters:
- name: CLUSTER_NAMESPACE
  description: "The project where the RHDG cluster will be installed."
  required: false
  value: "rhdg8"
- name: CLUSTER_NAME
  description: "The name of the RHDG cluster."
  required: false
  value: "rhdg"
