apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhdg8-monitoring
  annotations:
    description: Template to configure the monitoring stack for a RHDG cluster on OCP.
    tags: infinispan,datagrid,operator
    iconClass: icon-datagrid
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      k8s-app: prometheus
      jirakey: one
    name: datagrid-${CLUSTER_NAME}-monitoring
    namespace: ${CLUSTER_NAMESPACE}
  spec:
# Docu: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#servicemonitor
    endpoints:
      - targetPort: 11222 
        path: /metrics 
        honorLabels: true
        basicAuth:
          username:
            key: username
            name: ${CLUSTER_NAME}-monitoring-credentials
          password:
            key: password
            name: ${CLUSTER_NAME}-monitoring-credentials
        interval: 30s
        scrapeTimeout: 10s
        scheme: http 
        # tlsConfig:
        #   insecureSkipVerify: true
        #   serverName: ${CLUSTER_NAME} 
# Docu: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#relabelconfig
        # metricRelabelings:
        #   - sourceLabels: [clusterName]
        #     targetLabel: bu_code
        #     regex: (.*)
        #     replacement: ${1}
        #     action: replace
    namespaceSelector:
      matchNames:
        - ${CLUSTER_NAMESPACE} 
    selector:
      matchLabels:
        app: infinispan-service
        clusterName: ${CLUSTER_NAME}
    targetLabels:
      - clusterName
parameters:
- name: CLUSTER_NAMESPACE
  description: "The project where the RHDG cluster will be installed."
  required: false
  value: "rhdg8"
- name: CLUSTER_NAME
  description: "The name of the RHDG cluster."
  required: false
  value: "rhdg"