apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhdg8-operator
  annotations:
    description: Template to deploy a RHDG operator on OCP.
    tags: infinispan,datagrid,operator
    iconClass: icon-datagrid
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${OPERATOR_NAMESPACE}
    annotations:
      openshift.io/description: "This project contains all the resources related to the operator of Red Hat Data Grid 8"
      openshift.io/display-name: "RH Data Grid 8 - Operator"
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${CLUSTER_NAMESPACE_XSITE_A}
    annotations:
      openshift.io/description: "This project contains a cluster site of the Cross Data Center replicated set of Red Hat Data Grid 8 clusters"
      openshift.io/display-name: "RH Data Grid 8 - ${CLUSTER_NAMESPACE_XSITE_A}"
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${CLUSTER_NAMESPACE_XSITE_B}
    annotations:
      openshift.io/description: "This project contains a cluster site of the Cross Data Center replicated set of Red Hat Data Grid 8 clusters"
      openshift.io/display-name: "RH Data Grid 8 - ${CLUSTER_NAMESPACE_XSITE_B}"
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: datagrid
    namespace: ${OPERATOR_NAMESPACE}
  spec:
    targetNamespaces:
      - ${CLUSTER_NAMESPACE_XSITE_A}
      - ${CLUSTER_NAMESPACE_XSITE_B}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: datagrid-operator
    namespace: ${OPERATOR_NAMESPACE}
  spec:
    channel: 8.1.x
    installPlanApproval: Automatic 
    name: datagrid
    source: redhat-operators
    sourceNamespace: openshift-marketplace
parameters:
- name: OPERATOR_NAMESPACE
  description: "The project where the operator will be installed."
  required: false
  value: "rhdg8-xsite-operator"
- name: CLUSTER_NAMESPACE_XSITE_A
  description: "The name of the xsite RHDG cluster."
  required: false
  value: "rhdg8-xsite-01"
- name: CLUSTER_NAMESPACE_XSITE_B
  description: "The name of the xsite RHDG cluster."
  required: false
  value: "rhdg8-xsite-02"